version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t myapp -f Dockerfile .
      - echo "Scanning with Trivy..."
      - ./trivy image --exit-code 1 --severity HIGH,CRITICAL myapp
